name: Build, test and publish
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      project-path:
        /target:libs\Mvvm_Navigation_Core
        /target:libs\Mvvm_Navigation_Uno
        /target:libs\Mvvm_Navigation_Uno_WinUI
        /target:libs\Mvvm_Navigation_WinUI
        /target:libs\Mvvm_Navigation_Uwp
        /target:libs\Mvvm_Navigation_Wpf
        /target:libs\Mvvm_Navigation_Maui
        /target:libs\Mvvm_Navigation_Avalonia
      use-msbuild: true
      workloads: maui android ios maccatalyst macos
      install-tizen: true
      windows-sdk-version: 18362
      generate-build-number: false
      conventional-commits-publish-conditions: false
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}