name: Build, test and publish
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      project-path:
        src/libs/Mvvm.Navigation.Core/Mvvm.Navigation.Core.csproj
        src/libs/Mvvm.Navigation.Uno/Mvvm.Navigation.Uno.csproj
        src/libs/Mvvm.Navigation.Uno.WinUI/Mvvm.Navigation.Uno.WinUI.csproj
        src/libs/Mvvm.Navigation.WinUI/Mvvm.Navigation.WinUI.csproj
        src/libs/Mvvm.Navigation.Wpf/Mvvm.Navigation.Wpf.csproj
        src/libs/Mvvm.Navigation.Maui/Mvvm.Navigation.Maui.csproj
        src/libs/Mvvm.Navigation.Avalonia/Mvvm.Navigation.Avalonia.csproj
        
#        /target:libs\Mvvm_Navigation_Core
#        /target:libs\Mvvm_Navigation_Uno
#        /target:libs\Mvvm_Navigation_Uno_WinUI
#        /target:libs\Mvvm_Navigation_WinUI
#        #/target:libs\Mvvm_Navigation_Uwp
#        /target:libs\Mvvm_Navigation_Wpf
#        /target:libs\Mvvm_Navigation_Maui
#        /target:libs\Mvvm_Navigation_Avalonia
      #use-msbuild: true
      #install-latest-msbuild: true
      workloads: maui
      #install-tizen: true
      #windows-sdk-version: 18362
      generate-build-number: false
      conventional-commits-publish-conditions: false
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}