name: Build, test and publish
on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      project-path: Mvvm.Navigation.NuGet.slnf
        
#        /target:libs\Mvvm_Navigation_Core
#        /target:libs\Mvvm_Navigation_Uno
#        /target:libs\Mvvm_Navigation_Uno_WinUI
#        /target:libs\Mvvm_Navigation_WinUI
#        #/target:libs\Mvvm_Navigation_Uwp
#        /target:libs\Mvvm_Navigation_Wpf
#        /target:libs\Mvvm_Navigation_Maui
#        /target:libs\Mvvm_Navigation_Avalonia
      #use-msbuild: true
      #install-latest-msbuild: true
      workloads: maui
      #install-tizen: true
      #windows-sdk-version: 18362
      generate-build-number: false
      conventional-commits-publish-conditions: false
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}